// <auto-generated />
using System;
using LojaTitanica.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LojaTitanica.Migrations
{
    [DbContext(typeof(MySQLContext))]
    partial class MySQLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("LojaTitanica.Models.Cliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("LojaTitanica.Models.Item", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Produtoid")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int?>("Vendaid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Produtoid");

                    b.HasIndex("Vendaid");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("LojaTitanica.Models.Produto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("LojaTitanica.Models.Venda", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Clienteid")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Clienteid");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("LojaTitanica.Models.Item", b =>
                {
                    b.HasOne("LojaTitanica.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("Produtoid");

                    b.HasOne("LojaTitanica.Models.Venda", null)
                        .WithMany("Items")
                        .HasForeignKey("Vendaid");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("LojaTitanica.Models.Venda", b =>
                {
                    b.HasOne("LojaTitanica.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("Clienteid");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("LojaTitanica.Models.Venda", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
